import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Exemplo Boyler Plate",
  description: "Generated by create next app",
  keywords: "boyler, plate, exemplo",
};

export const viewport = {
  width: 1920,
  height: 1080,
  initialScale: 1.0,
  maximumScale: 5.0,
  colorScheme: 'dark'
}

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="pt-br">
      <body>
        <Cabecalho/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
