import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Exemplo Boyler Plate",
  description: "Generated by create next app",
  keywords: "Boyler Plate pronto"
};

export const viewport = {
  width: 1920,
  height: 1080,
  initialscale: 1.0,
  maximumScale: 5.0,
  colorScheme:'dark'
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
